### ISSUE TITLE
Help me with attached problems

### ISSUE THREAD

**Issue by dapeng313** [yiqin/Codility-Practice#2]
Some hours ago. I've toptal 2nd test with Codility.
Problems are aboves.
I didnt passed about it.
But i wanna know solutions.
Please give me your help with your talented skills.
Thanks.
[test.docx](https://github.com/yiqin/Codility-Practice/files/1165128/test.docx)

**Comment by yiqin** [comment]
@dapeng313 Could you post what's your progress? How did you try to solve the problem?
